// ---- src/strings.js ----
// A lookup table for UI strings, keyed by a dotted namespace.key (e.g.
// 'dashboard.notStarted'). Call `t('the.key')` where a literal used to be,
// optionally with a second argument for {placeholder}-style interpolation
// (e.g. `t('dashboard.periodCount', { count })` against a value of
// "{count} 節"). Every key must exist under 'zh-TW' - that's the fallback
// locale for anything missing from another one, and Orbit Class's original
// (and still primary) language, so it's treated as the source of truth.
const STRINGS = {
  'zh-TW': {
    'dashboard.notStarted': '尚未開始',
    'dashboard.schoolOver': '放學時間',
    'dashboard.noSchoolToday': '今日無課',
    'dashboard.betweenClasses': '下課',
    'dashboard.duringClass': '上課',
    'dashboard.seeYouWeekend': '週末愉快',
    'dashboard.seeYouTomorrow': '再見',
    'dashboard.seeYouMonday': '週一見',
    'dashboard.loading': '載入中…',
    'nlEdit.notConfigured': 'AI 課表編輯功能尚未設定，請聯絡課表管理者。',
    'nlEdit.offline': '目前沒有網路連線，AI 課表編輯暫時無法使用。',
    'nlEdit.viewerLocked': '此裝置為僅接收模式，無法使用 AI 課表編輯。如要自行編輯，請先解除同步。',
    'nlEdit.emptyInput': '請先輸入想修改的內容。',
    'nlEdit.working': '正在請求 AI 解析指令…',
    'nlEdit.ready': 'AI 已提出修改建議，請確認後套用。',
    'nlEdit.badResponse': 'AI 沒有回傳可辨識的修改建議，請換個說法再試。',
    'nlEdit.unclearTitle': '看不懂這個指令',
    'nlEdit.unclearMessage': 'AI 無法判斷這句話對應到哪一個修改動作，請換個說法再試。',
    'nlEdit.notFoundTitle': '找不到對應的課程或節次',
    'nlEdit.notFoundMessage': 'AI 判斷這個指令提到的星期、節次或課程在目前課表中不存在。',
    'nlEdit.noChangeTitle': '沒有變更',
    'nlEdit.noChangeMessage': 'AI 提出的修改內容跟目前課表完全相同，沒有需要套用的變更。',
    'nlEdit.confirmTitle': '要套用 AI 建議的修改嗎？',
    'nlEdit.confirmMessage': '會套用以下變更。',
    'nlEdit.confirmApply': '套用',
    'nlEdit.confirmCancel': '取消',
    'nlEdit.dismiss': '知道了',
    'common.apply': '套用',
    'common.back': '返回',
    'common.cancel': '取消',
    'common.copy': '複製',
    'common.delete': '刪除',
    'common.export': '匯出',
    'common.hide': '隱藏',
    'common.import': '匯入',
    'common.off': '關閉',
    'common.on': '開啟',
    'common.overwrite': '覆寫',
    'common.reset': '重設',
    'common.save': '儲存',
    'common.show': '顯示',
    'common.unknown': '未知',
    'weekday.sunday': '週日',
    'weekday.monday': '週一',
    'weekday.tuesday': '週二',
    'weekday.wednesday': '週三',
    'weekday.thursday': '週四',
    'weekday.friday': '週五',
    'weekday.saturday': '週六',
    'week.odd': '單週',
    'week.even': '雙週',
    'appearance.styleSaved': '樣式已儲存。',
    'appearance.emptySlot': '空位 {number}',
    'appearance.saveToSlot': '儲存至樣式 {number}',
    'appearance.overwritePersonalStyleTitle': '覆寫個人樣式？',
    'appearance.saveAsStyleTitle': '儲存為樣式 {number}？',
    'appearance.overwriteSlotMessage': '這會取代「{name}」目前儲存的配色。',
    'appearance.saveToSlotMessage': '目前的配色會存到第 {number} 個位置。',
    'appearance.styleSlotLabel': '樣式 {number}',
    'appearance.applySavedStyleTitle': '套用儲存樣式？',
    'appearance.currentStyleWillBeReplaced': '目前的樣式將被替換。',
    'appearance.styleNotAppliedTitle': '尚未套用樣式？',
    'appearance.leaveWillDiscardPreview': '離開將捨棄目前的樣式預覽。',
    'appearance.discardAndLeave': '捨棄並離開',
    'dashboard.closeTools': '關閉工具',
    'dashboard.openTools': '開啟工具',
    'dashboard.countdownDayUnit': '天',
    'dashboard.countdownAriaDays': '{name}倒數 {days} 天',
    'dashboard.countdownToday': '今天',
    'dashboard.countdownAriaStartsToday': '{name}今天開始',
    'dashboard.countdownInProgress': '進行中',
    'dashboard.countdownAriaInProgress': '{name}進行中',
    'dashboard.countdownEnded': '已結束',
    'dashboard.countdownAriaEnded': '{name}已結束',
    'dashboard.inProgress': '進行中',
    'dashboard.nextPeriod': '下一節',
    'dashboard.noClassesToday': '這天沒有課',
    'dashboard.restOrStudy': '可以休息或安排自習',
    'dashboard.periodNumber': '第 {number} 節',
    'dashboard.typeSplit': '雙週',
    'dashboard.typeFixed': '固定',
    'dashboard.teacherLabel': '教師　',
    'dashboard.periodCount': '{count} 節',
    'dashboard.noOccurrences': '無排課',
    'editorSchedule.invalidTimeRange': '{label}時間必須是有效的開始與結束時間。',
    'editorSchedule.periodLabel': '第 {number} 節',
    'editorSchedule.breakLabel': '特殊時段「{name}」',
    'editorSchedule.timeConflict': '時間衝突：{labelA} 與 {labelB} 重疊。',
    'editorSchedule.deletePeriod': '刪除節次',
    'editorSchedule.deletePeriodTitle': '刪除第 {number} 節？',
    'editorSchedule.deletePeriodMessage': '這會移除第 {number} 節的課程，後面的節次會往前移。',
    'editorSchedule.namePlaceholder': '名稱',
    'editorSchedule.deleteBreak': '刪除特殊時段',
    'editorSchedule.timeOverlapTitle': '時間有重疊',
    'editorSchedule.timeOverlapMessage': '請調整時間，避免課堂與特殊時段重疊。',
    'editorSchedule.goAdjustTime': '前往調整時間',
    'editorSchedule.backToEditing': '返回編輯',
    'editorTeachers.unnamedSubject': '未命名科目',
    'editorTeachers.assignSubtitle': '選擇「{label}」要放置的星期與節次',
    'editorTeachers.periodCurrentlyIs': '第 {number} 節目前是：{value}',
    'editorTeachers.periodBlank': '第 {number} 節（空白）',
    'editorTeachers.overwriteSlotTitle': '覆蓋這個時段？',
    'editorTeachers.overwriteSlotMessage': '第 {number} 節：「{from}」改成「{to}」？',
    'editorTeachers.confirmOverwrite': '確定覆蓋',
    'editorTeachers.deleteTitle': '刪除「{label}」？',
    'editorTeachers.deleteMessage': '這會移除這個課程，並清空所有使用它的課表格子。',
    'onboarding.startChoiceTitle': '怎麼開始？',
    'onboarding.startChoiceMessage': '手動建立課表，或用 AI 辨識照片自動產生課表。',
    'onboarding.useAiPhoto': '用 AI 辨識照片',
    'onboarding.buildManually': '前往手動建立',
    'onboarding.welcomeTitle': '開始使用 Orbit Class',
    'onboarding.welcomeMessage': '有代碼可直接輸入加入，沒有的話可以自己建立。',
    'onboarding.enterPairingCode': '輸入配對代碼',
    'onboarding.buildOwnFirst': '先自己建立',
    'editorBackup.overwriteExportTitle': '覆寫匯出內容？',
    'editorBackup.overwriteExportMessage': '匯出會覆寫目前文字欄位中的內容。',
    'editorBackup.overwriteExportConfirm': '確定要以新內容取代嗎？',
    'editorBackup.overwriteAndExport': '覆寫並匯出',
    'editorBackup.saveFirstTitle': '要先儲存目前設定嗎？',
    'editorBackup.saveFirstMessage': '有尚未儲存的變更，是否先儲存再{action}？',
    'editorBackup.saveThenAction': '儲存後{action}',
    'editorBackup.actionWithoutSaving': '不儲存直接{action}',
    'editorBackup.pasteBackup': '請貼上 Orbit Color 課表設定備份。',
    'editorBackup.noCompressionExport': '此裝置不支援壓縮匯出。',
    'editorBackup.noCompressionImport': '此裝置不支援壓縮匯入。',
    'editorBackup.mustBeJsonObject': '設定文字必須是 JSON 物件。',
    'editorBackup.notCreatedByThisApp': '設定檔不是由目前版本的 Orbit_Color 建立。',
    'editorBackup.missingField': '設定文字缺少「{field}」。',
    'editorBackup.mustBeObject': '{field} 必須是物件。',
    'editorBackup.mustBeArray': '{field} 必須是陣列。',
    'editorBackup.teacherDbShape': 'teacherDB 必須是每個項目都是 [科目, 老師, 教室] 陣列。',
    'editorBackup.weeklyScheduleShape': 'weeklySchedule 必須是每一天都是陣列。',
    'editorBackup.scheduleUnknownTeacher': '排課資料包含不存在的教師代碼。',
    'editorBackup.invalidBellTimes': '節次時間必須是有效的開始與結束時間。',
    'editorBackup.copyFailed': '無法自動複製匯出內容。',
    'editorBackup.exportSuccess': '已產生並複製匯出內容。',
    'editorBackup.exportFailed': '匯出失敗：無法建立設定備份。',
    'editorBackup.blankValue': '（空白）',
    'editorBackup.emptyValue': '（空）',
    'editorBackup.unnamedClass': '（未命名課程）',
    'editorBackup.dayNumber': '第 {day} 天',
    'editorBackup.added': '新增 {item}',
    'editorBackup.removed': '移除 {item}',
    'editorBackup.subjectChange': '{ref} 科目：{before} -> {after}',
    'editorBackup.teacherChange': '{ref} 老師：{before} -> {after}',
    'editorBackup.sectionTeachers': '課程與老師',
    'editorBackup.teacherOrderChanged': '課程順序已調整。',
    'editorBackup.locationChange': '{ref} 地點：{before} -> {after}',
    'editorBackup.sectionLocations': '上課地點',
    'editorBackup.noneValue': '（無）',
    'editorBackup.periodChange': '第 {number} 節：{before} -> {after}',
    'editorBackup.sectionBellTimes': '節次時間',
    'editorBackup.breakChange': '休息時段 {number}：{before} -> {after}',
    'editorBackup.sectionBreakTimes': '休息時段',
    'editorBackup.scheduleCellChange': '{day}第 {number} 節：{before} -> {after}',
    'editorBackup.sectionScheduleContent': '課表內容',
    'editorBackup.eventChanged': '活動：{before} -> {after}',
    'editorBackup.eventAdded': '新增活動：{event}',
    'editorBackup.eventRemoved': '移除活動：{event}',
    'editorBackup.sectionCountdownEvents': '倒數活動',
    'editorBackup.countdownOrderChanged': '倒數活動順序已調整。',
    'editorBackup.reverseWeekChange': '單雙週對調：{before} -> {after}',
    'editorBackup.colorChangeImport': '{label}（目前）：{before} -> {label}（匯入）：{after}',
    'editorBackup.colorChangePlain': '{label}：{before} -> {after}',
    'editorBackup.primaryColor': '主色',
    'editorBackup.secondaryColor': '次色',
    'editorBackup.sectionCurrentStyle': '目前樣式',
    'editorBackup.styleSlotLabel': '樣式 {number}',
    'editorBackup.unnamedStyle': '未命名',
    'editorBackup.styleSlotAdded': '新增{slot}「{name}」：主色 {primary}，次色 {secondary}',
    'editorBackup.styleSlotRemoved': '移除{slot}「{name}」：主色 {primary}，次色 {secondary}',
    'editorBackup.styleSlotChangedImport':
      '{slot}「{before}」 -> 「{after}」：主色（目前）{beforePrimary} -> 主色（匯入）{afterPrimary}，次色（目前）{beforeSecondary} -> 次色（匯入）{afterSecondary}',
    'editorBackup.styleSlotChangedPlain':
      '{slot}「{before}」 -> 「{after}」：主色 {beforePrimary} -> {afterPrimary}，次色 {beforeSecondary} -> {afterSecondary}',
    'editorBackup.sectionPersonalStyles': '個人樣式',
    'editorBackup.noChanges': '沒有變更。',
    'editorBackup.importFailedIdentical': '匯入失敗：設定內容與目前設定相同。',
    'editorBackup.importFailedInvalid': '匯入失敗：內容無效或已損毀。',
    'editorBackup.mergedClass': '合併課程「{name}」（名稱相同，使用匯入的課程資料）',
    'editorBackup.addedClass': '新增課程「{name}」',
    'editorBackup.replacedClassLocation': '取代課程「{name}」地點：{before} -> {after}',
    'editorBackup.replacedDayPeriod': '取代{day}第 {number} 節：{before} -> {after}',
    'editorBackup.addedDayPeriod': '新增{day}第 {number} 節：{value}',
    'editorBackup.replacedBellTimes': '取代節次時間',
    'editorBackup.addedBreak': '新增特殊時段「{name}」',
    'editorBackup.mergedBreak': '合併特殊時段「{name}」',
    'editorBackup.replacedBreak': '取代特殊時段「{name}」：{before} -> {after}',
    'editorBackup.removedBreakConflict': '移除特殊時段「{name}」（與匯入的節次時間衝突）',
    'editorBackup.addedCountdown': '新增倒數活動：{name}（{date}）',
    'editorBackup.mergedCountdown': '合併倒數活動：{name}（{date}）',
    'editorBackup.replacedCountdown': '取代倒數活動：{name}（{before} -> {after}）',
    'editorBackup.replacedReverseWeek': '取代單雙週設定：{value}',
    'editorBackup.importModeTitle': '匯入方式？',
    'editorBackup.importModeMessage': '要合併目前設定與匯入設定嗎？',
    'editorBackup.importModeHint': '合併匯入會保留可共存內容；課表時間衝突時使用匯入內容。',
    'editorBackup.mergeImport': '合併匯入',
    'editorBackup.directImport': '直接匯入',
    'editorBackup.importFailedWithReason': '匯入失敗：{reason}',
    'editorBackup.importFailedTitle': '匯入失敗',
    'editorBackup.importFailedMessage': '無法完成這次匯入，請調整後再試一次。',
    'editorBackup.diffAdded': '新增：',
    'editorBackup.diffMerged': '合併：',
    'editorBackup.diffReplaced': '取代：',
    'editorBackup.confirmMergeImportTitle': '確認合併匯入？',
    'editorBackup.confirmDirectImportTitle': '確認直接匯入？',
    'editorBackup.identicalImportMessage': '匯入內容與目前設定完全相同，仍可匯入。',
    'editorBackup.mergeImportHint': '以下分開列出新增、合併與取代的內容。',
    'editorBackup.directImportWarning': '匯入設定將取代目前已儲存的課表資料。',
    'editorBackup.identicalImportDetail': '內容相同，沒有需要變更的項目。',
    'editorBackup.confirmMerge': '確認合併',
    'editorBackup.confirmImport': '確認匯入',
    'editorBackup.updatedFromOtherDevice': '已從其他裝置更新',
    'editorBackup.saved': '已儲存',
    'editorBackup.importedAndSaved': '已匯入並儲存，編輯器已更新為貼上的設定。',
    'editorBackup.resetAllTitle': '重設所有資料？',
    'editorBackup.resetAllMessage': '會清除所有資料並回到初始畫面，此動作無法復原。',
    'editorBackup.resetAllDetail': '課表、樣式、同步設定等皆會清除；其他同步裝置不受影響。',
    'editorBackup.noFileSelected': '尚未選擇檔案',
    'nlEdit.invalidJsonResponse': 'AI 回傳的內容不是有效的 JSON：{message}',
    'nlEdit.cannotConnect': '無法連線至 AI 服務：{message}',
    'nlEdit.locationBlocked':
      'AI 服務暫時因伺服器所在地區限制而無法使用（節點：{colo}），這通常只是暫時性的網路路由問題，請稍後再試一次。',
    'nlEdit.parseFailedWithStatus': 'AI 指令解析失敗（{status}）：{message}',
    'nlEdit.parseFailedNoModel': 'AI 指令解析失敗：沒有可用的模型。',
    'nlEdit.locationBlockedRetrying':
      'AI 服務因伺服器所在地區限制暫時無法使用（節點：{colo}），正在自動重試（第 {attempt} 次）…',
    'sync.rateLimited': '請求過於頻繁，請稍後再試。',
    'sync.createFailed': '建立同步失敗：{message}',
    'sync.notConfigured': '尚未設定同步。',
    'sync.uploadFailed': '同步上傳失敗：{message}',
    'sync.downloadFailed': '同步下載失敗：{message}',
    'sync.syncedFromOtherDevice': '已從其他裝置同步課表。',
    'sync.remoteDeletedByManager':
      '同步已被管理者整個刪除，這台裝置已自動解除同步（本機課表不受影響）。',
    'sync.copied': '已複製！',
    'sync.copyFailed': '複製失敗：{message}',
    'sync.roleViewer': '身份：僅接收（唯讀）— 課表會自動更新，但這台裝置無法編輯。',
    'sync.roleManager': '身份：管理者 — 可以編輯課表，變更會同步到其他裝置。',
    'sync.stopSyncingStyleTitle': '不再同步樣式顏色？',
    'sync.resumeSyncingStyleTitle': '恢復同步樣式顏色？',
    'sync.stopSyncingStyleMessage': '會保留這台裝置目前的配色，不再套用其他裝置的樣式。',
    'sync.resumeSyncingStyleMessage': '共用的配色與樣式預設會立刻套用到這台裝置。',
    'sync.stopSyncingStyleDetail': '課表內容仍照常同步。',
    'sync.resumeSyncingStyleDetail': '目前的配色與樣式預設會先備份起來。',
    'sync.stopSyncingStyle': '不再同步樣式',
    'sync.resumeSyncing': '恢復同步',
    'sync.styleBackupRestored': '已還原保留的樣式與樣式預設。',
    'sync.recoverKeptColorsTitle': '找回先前保留的配色？',
    'sync.recoverKeptColorsMessage': '要換回上次保留的配色與樣式預設，還是繼續使用目前的？',
    'sync.switchToKeptColors': '換回保留的配色',
    'sync.keepCurrentColors': '繼續使用目前配色',
    'sync.scheduleBackupRestored': '已還原加入同步前的本機課表。',
    'sync.recoverPreJoinScheduleTitle': '找回加入同步前的課表？',
    'sync.recoverPreJoinScheduleMessage': '要換回舊課表，還是繼續使用剛同步的課表？',
    'sync.switchToPreJoinSchedule': '換回加入前的課表',
    'sync.keepCurrentSchedule': '繼續使用目前課表',
    'sync.editLockedTitle':
      '此裝置僅接收同步，無法編輯課表。輸入管理者密碼即可取得編輯權限，或先在「同步 / 匯入匯出」解除同步。',
    'sync.editTitle': '編輯課表',
    'sync.styleLockedTitle':
      '此裝置正在同步樣式，無法自行變更。若要自訂樣式，請先在同步面板勾選「不同步樣式顏色」。',
    'sync.styleToolTitle': '樣式工具',
    'sync.syncNotConfiguredContactAdmin': '跨裝置同步功能尚未設定，請聯絡課表管理者。',
    'sync.offlineCannotCreate': '目前沒有網路連線，無法建立同步。',
    'sync.createNewSyncTitle': '建立新同步？',
    'sync.createNewSyncMessage': '會產生一組新的同步代碼與管理者密碼。',
    'sync.createNewSyncDetail': '已有代碼的話請改用「加入同步」，名額有限。',
    'sync.createNewSync': '建立新同步',
    'sync.creating': '正在建立同步…',
    'sync.offlineCannotJoin': '目前沒有網路連線，無法加入同步。',
    'sync.enterPairingCode': '請輸入配對代碼。',
    'sync.checkingCode': '正在檢查配對代碼…',
    'sync.codeNotFound': '找不到這組配對代碼，請確認代碼是否正確，或請對方先按「建立新同步」。',
    'sync.wrongManagerPasscode': '管理者密碼不正確，請確認後再試一次。',
    'sync.roleManagerLabel': '管理者',
    'sync.roleViewerOnlyLabel': '僅接收者',
    'sync.joinSyncTitle': '加入同步？',
    'sync.joinSyncMessage': '以「{role}」加入，會取代這台裝置目前的課表，無法復原。',
    'sync.joinSyncDetail': '其他裝置的課表不受影響。',
    'sync.joinAnyway': '仍要加入',
    'sync.joining': '正在加入同步…',
    'sync.wrongManagerPasscodeNotJoined': '管理者密碼不正確，尚未加入同步。',
    'sync.joinedAsManager': '已以管理者身份加入同步。',
    'sync.joinedAsViewer': '已加入同步（僅接收）。',
    'sync.offlineCannotVerify': '目前沒有網路連線，無法驗證管理者密碼。',
    'sync.enterManagerPasscode': '請輸入管理者密碼。',
    'sync.verifyingPasscode': '正在驗證管理者密碼…',
    'sync.codeNotFoundMaybeDeleted': '找不到這組配對代碼，可能已被整個刪除同步。',
    'sync.wrongManagerPasscodePlain': '管理者密碼不正確。',
    'sync.gotManagerAccess': '已取得管理者權限，現在可以編輯課表了。',
    'sync.unlinkCopyText': '同步代碼：{code}\n管理者密碼：{passcode}',
    'sync.unlinkTitle': '解除同步？',
    'sync.unlinkMessageManager':
      '這只會讓這台裝置變回本機課表，其他裝置仍會繼續同步。忘記代碼前可先複製備用：',
    'sync.unlinkMessageViewer': '解除後會變回本機課表，並忘記這組配對代碼；建議先複製備用：',
    'sync.unlink': '解除同步',
    'sync.unlinked': '已解除同步（不影響本機課表）。',
    'sync.deleteForEveryone': '整個刪除同步',
    'sync.copyCode': '複製代碼',
    'sync.offlineCannotDelete': '目前沒有網路連線，無法刪除同步。',
    'sync.deleteAllTitle': '整個刪除這組同步？',
    'sync.deleteAllMessage': '會刪除伺服器上的共用課表，此動作無法復原。',
    'sync.deleteAllDetail':
      '代碼「{code}」與管理者密碼立即失效，所有裝置之後同步時會各自變回本機課表。',
    'sync.deleteAll': '整個刪除',
    'sync.deleting': '正在刪除同步…',
    'sync.deleteFailed': '刪除失敗：{error}',
    'sync.deletedForEveryone': '已整個刪除同步，所有裝置都已斷開連結（本機課表不受影響）。',
    'sync.viewerLockedImport': '此裝置為僅接收模式，無法匯入。如要自行編輯，請先解除同步。',
    'sync.viewerLockedSave': '此裝置為僅接收模式，無法儲存變更。如要自行編輯，請先解除同步。',
    'testsim.start': '開始',
    'testsim.pause': '暫停',
    'testsim.resume': '繼續',
    'testsim.versionLabel': '版本',
    'testsim.checking': '檢查中…',
    'testsim.checkForUpdate': '檢查更新',
    'testsim.upToDate': '已是最新版本',
    'testsim.checkFailed': '檢查失敗，請確認網路連線',
    'testsim.updating': '更新中…',
    'editorCore.unnamedClassLabel': '未命名',
    'editorCore.scheduleImpactLine': '{day}第 {number} 節：{ref}',
    'editorCore.offlineMessage': '目前沒有網路連線，AI 匯入與跨裝置同步暫時無法使用。',
    'editorCore.dragToReorder': '拖曳排序',
    'editorCore.expandToEdit': '展開編輯',
    'editorCore.eventNameLabel': '活動名稱',
    'editorCore.dateLabel': '日期',
    'editorCore.startDateLabel': '開始日期',
    'editorCore.endDateLabel': '結束日期',
    'editorCore.orderLabel': '順序',
    'editorCore.countdownOrderAriaLabel': '倒數活動順序',
    'editorCore.removeCountdownAriaLabel': '移除倒數',
    'editorCore.countdownEventFallback': '倒數活動',
    'editorCore.dragCountdownReorderAriaLabel': '拖曳倒數活動排序',
    'editorCore.backToSchedule': '返回課表',
    'editorCore.discardChangesTitle': '捨棄變更？',
    'editorCore.discardChangesMessage': '以下尚未儲存的變更將不會套用。',
    'editorCore.discard': '捨棄',
    'editorCore.unimportedContentTitle': '尚未匯入內容？',
    'editorCore.discardAndLeaveTransfer': '捨棄離開',
    'editorCore.saveChangesTitle': '要儲存嗎？',
    'editorCore.saveChangesMessage': '會套用以下變更。',
    'editorCore.unimportedPastedAndAiWarning': '未匯入的貼上內容與 AI 辨識結果將被清除。',
    'editorCore.unimportedPastedWarning': '未匯入的貼上內容將被清除。',
    'editorCore.unimportedAiWarning': '未匯入的 AI 辨識結果將被清除。',
    'editorCore.unimportedGenericWarning': '未匯入內容將被清除。',
    'editorCore.clearedUnimportedContent': '已清除未匯入內容。',
    'editorCore.aiRecognizingTitle': 'AI 辨識中',
    'editorCore.aiRecognizingMessage': '請等辨識完成再關閉，否則結果會遺失。',
    'geminiOcr.selectAFile': '請選擇一個檔案。',
    'geminiOcr.unsupportedFileFormat': '不支援的檔案格式：{name}（可用 JPG／PNG／HEIC／PDF）。',
    'geminiOcr.unnamedFile': '未命名檔案',
    'geminiOcr.fileTooLarge': '檔案太大：{name}，請改用較小的檔案。',
    'geminiOcr.imageLoadFailed': '圖片載入失敗，請換一張再試。',
    'geminiOcr.imageResolutionTooLow': '圖片解析度過低，請換一張更清楚的照片。',
    'geminiOcr.imageEncodeFailed': '圖片編碼失敗，請換一張再試。',
    'geminiOcr.fileReadFailed': '檔案讀取失敗，請再試一次。',
    'geminiOcr.notConfigured': 'AI 匯入功能尚未設定，請聯絡課表管理者。',
    'geminiOcr.offline': '目前沒有網路連線，AI 匯入暫時無法使用。',
    'geminiOcr.selectFileFirst': '請先選擇檔案。',
    'geminiOcr.requestingModel': '正在請求 AI 模型（{model}）分析課表…',
    'geminiOcr.connectionFailedNextModel': '連線失敗，準備改用下一個模型…',
    'geminiOcr.aiRespondedParsing': 'AI 已回應（使用模型：{model}），正在解析辨識結果…',
    'geminiOcr.resultIncompleteRetryStronger':
      '模型（{model}）的結果不完整，改用更強的模型再試一次…',
    'geminiOcr.serviceUnavailable': 'AI 服務目前無法使用，請稍後再試。',
    'geminiOcr.recognitionFailedWithStatus': 'AI 辨識請求失敗（{status}）：{message}',
    'geminiOcr.modelUnavailableNextModel':
      '模型（{model}）暫時無法使用（{status}：{message}），準備改用下一個模型…',
    'geminiOcr.recognitionFailedNoModel': 'AI 辨識請求失敗：沒有可用的模型。',
    'geminiOcr.noScheduleContent': 'AI 沒有回傳任何課表內容，請換一張更清楚的照片再試。',
    'geminiOcr.lunchBreakFallback': '午休',
    'geminiOcr.filePrefixedMessage': '檔案 {number}：{message}',
    'geminiOcr.noScheduleOrCountdownDetected':
      '沒有偵測到課表圖片或倒數活動，請確認上傳的檔案中至少有一張完整的每週課表照片、選課紀錄，或含有日期的倒數活動通知。',
    'geminiOcr.noValidScheduleData': 'AI 沒有回傳有效的課表資料。',
    'geminiOcr.noClassesOrCountdownDetected': '沒有辨識到課程或倒數日期。',
    'geminiOcr.bellTimesFormatInvalid': '節次時間資料格式不正確。',
    'geminiOcr.someBellTimesFormatInvalid': '部分節次時間格式不正確。',
    'geminiOcr.scheduleDataFormatInvalid': '課表資料格式不正確。',
    'geminiOcr.periodsOverlapWarning': '第 {a} 節與第 {b} 節的時間重疊，請確認鐘聲時間是否正確。',
    'geminiOcr.breakClassOverlapWarning':
      '{day}第 {period} 節與「{name}」時段重疊，但仍排了課程「{subject}」，請確認是否誤植。',
    'geminiOcr.doubleBookedWarning':
      '{day}第 {periodA} 節「{subjectA}」與第 {periodB} 節「{subjectB}」時間重疊，可能是衝堂。',
    'geminiOcr.periodEndNotAfterStart':
      '第 {number} 節的結束時間不晚於開始時間，請確認鐘聲時間是否正確。',
    'geminiOcr.periodTooShort': '第 {number} 節只有 {minutes} 分鐘，可能是鐘聲時間辨識錯誤。',
    'geminiOcr.periodTooLong': '第 {number} 節長達 {hours} 小時，可能是鐘聲時間辨識錯誤。',
    'geminiOcr.reviewBeforeImport': '請確認並視需要修改下方內容，再按下方按鈕匯入。',
    'geminiOcr.reviewAboveBeforeImport': '請確認以上內容無誤，再按下方按鈕匯入。',
    'geminiOcr.waitedSeconds': '已等待 {seconds} 秒',
    'geminiOcr.estimatedWaitTime': '預估等待時間 約 {seconds} 秒',
    'geminiOcr.longerThanEstimated': '比預估久一點，仍在辨識中…',
    'geminiOcr.oneFileSelected': '已選擇 1 個檔案',
    'geminiOcr.filesSelectedWithNames': '已選擇 {count} 個檔案：{names}',
    'geminiOcr.tooManyFiles': '一次最多 {max} 個檔案，請減少後再試。',
    'geminiOcr.loadedMultipleFiles':
      '已載入 {count} 個檔案，AI 會自動判斷每個檔案的內容（課表或選課資料），順序不影響結果。',
    'geminiOcr.loadedSingleFile': '已載入檔案，點擊匯入讓 AI 自動判讀課表。',
    'geminiOcr.viewerLockedImport':
      '此裝置為僅接收模式，無法使用 AI 匯入。如要自行編輯，請先解除同步。',
    'geminiOcr.preparingMultipleFiles': '準備 {count} 個檔案中…',
    'geminiOcr.preparingFile': '準備檔案中…',
    'geminiOcr.validatingScheduleData': '正在驗證課表資料…',
    'geminiOcr.recognitionCompleteReview':
      '課表辨識完成（模型：{model}），請確認下方內容後進行匯入。',
    'geminiOcr.recognitionIncompleteManualFix': 'AI 辨識結果不完整，請手動修正後再匯入。',
    'geminiOcr.importPreviewFailed': '匯入預覽失敗：{message}',
    'editorTeachers.subjectPlaceholder': '科目',
    'editorTeachers.teacherPlaceholder': '教師',
    'editorTeachers.locationPlaceholderOptional': '教室(選填)',
    'editorTeachers.subjectTeacherOrderAriaLabel': '科目教師順序',
    'editorTeachers.assignPeriodAriaLabel': '指定課節',
    'editorTeachers.assignButtonLabel': '排課',
    'testsim.simulating': '模擬中',
    'dashboard.toolsLabel': '工具',
    'sync.transferSheetTitle': '同步 / 匯入匯出',
    'appearance.openStyleTools': '開啟樣式工具',
    'dashboard.nextPeriodInfoAriaLabel': '下一節資訊',
    'dashboard.thisWeekLabel': '本週',
    'dashboard.nextWeekLabel': '下週',
    'dashboard.periodsPerWeekLabel': '每週節數',
    'dashboard.typeLabel': '類型',
    'dashboard.locationLabel': '教室',
    'dashboard.occurrencesLabel': '排課',
    'common.done': '完成',
    'editorTeachers.assignSheetTitle': '排課',
    'editorTeachers.chooseWeekdayAriaLabel': '選擇星期',
    'editorTeachers.applyAndFinish': '套用並完成',
    'editorCore.optionsFoldLabel': '選項',
    'editorSchedule.reverseWeekToggleLabel': '單雙週對調',
    'editorCore.addCountdownButton': '新增倒數',
    'editorCore.countdownHint':
      '首頁顯示第一個倒數活動，可在首頁左右滑動切換。日期可設定一段範圍（例如考試週），單日活動請將開始與結束日期設為同一天。',
    'editorTeachers.subjectsAndTeachersFoldLabel': '科目與教師',
    'common.add': '新增',
    'editorTeachers.splitWeekHintTitle': '雙週科目／教師',
    'editorTeachers.splitWeekHintBody': '兩週不同時以「／」分隔（例：國文／公民）',
    'editorCore.scheduleFoldLabel': '課表',
    'nlEdit.headingLabel': 'AI 課表編輯',
    'nlEdit.confirmBeforeApplyTag': '套用前會先確認',
    'nlEdit.hintBody': '用一句話描述想改的內容，可一次講多件事，AI 會先提出建議，確認後才套用。',
    'common.submit': '送出',
    'editorCore.drillPeriods': '節次',
    'editorCore.drillBreaks': '時段',
    'editorCore.drillCountdown': '倒數',
    'editorSchedule.addPeriodButton': '新增節次',
    'editorSchedule.specialTimeFoldLabel': '特殊時段',
    'editorSchedule.addSpecialTimeButton': '新增特殊時段',
    'sync.syncHeading': '同步',
    'sync.syncHeadingTag': '持續、跨裝置自動保持一致',
    'sync.setupHint':
      '課表自動同步到所有裝置，不需要帳號。同步代碼可自由分享；管理者密碼才能編輯課表，請妥善保管。',
    'sync.orJoinExisting': '或加入現有同步',
    'sync.enterSyncCodePlaceholder': '輸入同步代碼',
    'sync.haveManagerPasscodeSummary': '我有管理者密碼，也想要能編輯課表',
    'sync.enterManagerPasscodePlaceholder': '輸入管理者密碼',
    'sync.joinSyncButton': '加入同步',
    'sync.createdHint': '同步已建立！請先保存好管理者密碼，離開後不會再直接顯示。',
    'sync.codeLabelShareable': '同步代碼（可自由分享）',
    'sync.managerPasscodeLabelKeepSafe': '管理者密碼（請妥善保管）',
    'sync.savedCodeAndPasscode': '我已保存好代碼與密碼',
    'sync.pairedShareHint': '已配對同步，分享代碼給其他裝置即可加入：',
    'sync.enterPasscodeForEditAccess': '輸入管理者密碼以取得編輯權限',
    'sync.getEditAccessButton': '取得編輯權限',
    'sync.dontSyncStyleCheckboxLabel': '不同步樣式顏色（保留這台裝置目前的配色）',
    'geminiOcr.headingLabel': 'AI 匯入',
    'geminiOcr.oneTimeImportTag': '單次匯入，不會自動同步',
    'geminiOcr.setupHint':
      '選擇課表照片、截圖或 PDF，AI 自動判讀並產出課表。可選多個檔案一起讀取（例如課表照片＋選課截圖）。',
    'geminiOcr.selectFileLabel': '選擇檔案',
    'geminiOcr.filePreviewAlt': '檔案預覽',
    'editorBackup.manualBackupLegacySummary': '手動備份（舊版，不需要同步也能用）',
    'editorBackup.pasteBackupPlaceholder':
      '請在此貼上 Orbit Class 課表設定備份，或按下「匯出」建立備份。',
    'editorBackup.copyFullBackupHint': '請複製完整備份文字，包含 BEGIN 與 END 標記。',
    'testsim.advancedFoldSummary': '進階：時間模擬',
    'testsim.previewHint': '預覽指定時間的課表效果，不影響實際資料。',
    'testsim.openTimeSimButton': '開啟時間模擬',
    'geminiOcr.previewTitle': '辨識結果與匯入預覽',
    'geminiOcr.warningsTitle': '可能需要注意',
    'geminiOcr.classesFoldLabel': '課程',
    'geminiOcr.assignmentFoldLabel': '課表指派',
    'geminiOcr.countdownDatesFoldLabel': '倒數日期',
    'geminiOcr.confirmAndImportButton': '確認並匯入',
    'editorCore.unsavedTitle': '尚未儲存',
    'editorCore.leaveWillDiscardChanges': '離開將捨棄本次變更。',
    'testsim.timeSimAriaLabel': '時間模擬',
    'testsim.versionLoading': '版本載入中…',
    'editorBackup.resetAllDataAriaLabel': '重設所有資料',
    'editorCore.timeHourMinuteLabel': '時間（時／分）',
    'editorCore.minutesAriaLabel': '分',
    'testsim.startPauseHint': '「開始」後會自動走時；「暫停」後可改時間。',
    'testsim.exitSimButton': '結束模擬',
    'appearance.customColorFoldHeading': '自訂配色',
    'appearance.colorLabel': '顏色',
    'appearance.chooseColorAriaLabel': '選擇顏色',
    'appearance.styleLibraryFoldHeading': '樣式庫',
    'appearance.builtInPresetsLabel': '內建預設',
    'appearance.presetRose': '餘燼',
    'appearance.presetOcean': '潟湖',
    'appearance.presetMidnight': '墨夜',
    'appearance.presetGraphite': '柑橘',
    'appearance.presetAmber': '琥珀',
    'appearance.presetRuby': '胭脂',
    'appearance.presetLilac': '丁香',
    'appearance.myStylesLabel': '我的樣式',
    'appearance.styleSlotHint': '點空位旁的「＋」儲存目前配色，之後可直接點選套用。',
    'appearance.previewingNotSaved': '預覽中，尚未儲存',
    'appearance.exitPreviewButton': '離開預覽',
    'appearance.saveStyleButton': '儲存樣式',
    'appearance.previewAndSaveButton': '預覽並儲存',
    'common.close': '關閉',
    'editorCore.weekdayFieldLabel': '星期'
  },
  en: {
    'dashboard.notStarted': 'Not started yet',
    'dashboard.schoolOver': 'School is over',
    'dashboard.noSchoolToday': 'No classes today',
    'dashboard.betweenClasses': 'Break',
    'dashboard.duringClass': 'In class',
    'dashboard.seeYouWeekend': 'Have a great weekend',
    'dashboard.seeYouTomorrow': 'See you tomorrow',
    'dashboard.seeYouMonday': 'See you Monday',
    'dashboard.loading': 'Loading…',
    'nlEdit.notConfigured':
      'AI schedule editing has not been set up yet. Please contact your schedule administrator.',
    'nlEdit.offline':
      'You are currently offline, so AI schedule editing is temporarily unavailable.',
    'nlEdit.viewerLocked':
      'This device is in receive-only mode, so AI schedule editing is unavailable. Unlink sync first if you want to edit.',
    'nlEdit.emptyInput': 'Please enter what you would like to change first.',
    'nlEdit.working': 'Asking AI to parse the instruction…',
    'nlEdit.ready': 'AI has proposed a change. Please review and apply it.',
    'nlEdit.badResponse': "AI didn't return a recognizable change. Please try rephrasing.",
    'nlEdit.unclearTitle': "Couldn't understand this instruction",
    'nlEdit.unclearMessage':
      'AI could not determine which change this sentence refers to. Please try rephrasing.',
    'nlEdit.notFoundTitle': 'No matching class or period found',
    'nlEdit.notFoundMessage':
      'AI determined that the day, period, or class mentioned does not exist in the current schedule.',
    'nlEdit.noChangeTitle': 'No changes',
    'nlEdit.noChangeMessage':
      "AI's proposed change is identical to the current schedule, so there is nothing to apply.",
    'nlEdit.confirmTitle': "Apply AI's suggested change?",
    'nlEdit.confirmMessage': 'The following change will be applied.',
    'nlEdit.confirmApply': 'Apply',
    'nlEdit.confirmCancel': 'Cancel',
    'nlEdit.dismiss': 'Got it',
    'common.apply': 'Apply',
    'common.back': 'Back',
    'common.cancel': 'Cancel',
    'common.copy': 'Copy',
    'common.delete': 'Delete',
    'common.export': 'Export',
    'common.hide': 'Hide',
    'common.import': 'Import',
    'common.off': 'Off',
    'common.on': 'On',
    'common.overwrite': 'Overwrite',
    'common.reset': 'Reset',
    'common.save': 'Save',
    'common.show': 'Show',
    'common.unknown': 'Unknown',
    // Abbreviated (not "Sunday"/"Monday"/...) on purpose: every call site
    // (nav-bar day tabs, editor day labels/tabs, schedule-row day badges)
    // is a compact, fixed-width slot sized around the 2-character zh-TW
    // originals (週三 etc.) - a full English weekday name overflows those
    // slots and visually bleeds into the neighboring one (confirmed via a
    // real screenshot, not just reasoning about width). Also just the
    // normal convention for a calendar/schedule tab bar in English.
    'weekday.sunday': 'Sun',
    'weekday.monday': 'Mon',
    'weekday.tuesday': 'Tue',
    'weekday.wednesday': 'Wed',
    'weekday.thursday': 'Thu',
    'weekday.friday': 'Fri',
    'weekday.saturday': 'Sat',
    'week.odd': 'Odd week',
    'week.even': 'Even week',
    'appearance.styleSaved': 'Style saved.',
    'appearance.emptySlot': 'Empty slot {number}',
    'appearance.saveToSlot': 'Save to style {number}',
    'appearance.overwritePersonalStyleTitle': 'Overwrite personal style?',
    'appearance.saveAsStyleTitle': 'Save as style {number}?',
    'appearance.overwriteSlotMessage': 'This will replace the colors currently saved as "{name}".',
    'appearance.saveToSlotMessage': 'The current colors will be saved to slot {number}.',
    'appearance.styleSlotLabel': 'Style {number}',
    'appearance.applySavedStyleTitle': 'Apply saved style?',
    'appearance.currentStyleWillBeReplaced': 'The current style will be replaced.',
    'appearance.styleNotAppliedTitle': 'Style not applied yet?',
    'appearance.leaveWillDiscardPreview': 'Leaving will discard the current style preview.',
    'appearance.discardAndLeave': 'Discard and leave',
    'dashboard.closeTools': 'Close tools',
    'dashboard.openTools': 'Open tools',
    'dashboard.countdownDayUnit': 'days',
    'dashboard.countdownAriaDays': '{days} days left until {name}',
    'dashboard.countdownToday': 'Today',
    'dashboard.countdownAriaStartsToday': '{name} starts today',
    'dashboard.countdownInProgress': 'In progress',
    'dashboard.countdownAriaInProgress': '{name} is in progress',
    'dashboard.countdownEnded': 'Ended',
    'dashboard.countdownAriaEnded': '{name} has ended',
    'dashboard.inProgress': 'In progress',
    'dashboard.nextPeriod': 'Next period',
    'dashboard.noClassesToday': 'No classes on this day',
    'dashboard.restOrStudy': 'Feel free to rest or plan your own study time',
    'dashboard.periodNumber': 'Period {number}',
    'dashboard.typeSplit': 'Alternating weeks',
    'dashboard.typeFixed': 'Fixed',
    'dashboard.teacherLabel': 'Teacher　',
    'dashboard.periodCount': '{count} periods',
    'dashboard.noOccurrences': 'Not scheduled',
    'editorSchedule.invalidTimeRange': '{label} must have a valid start and end time.',
    'editorSchedule.periodLabel': 'Period {number}',
    'editorSchedule.breakLabel': 'special time slot "{name}"',
    'editorSchedule.timeConflict': 'Time conflict: {labelA} overlaps with {labelB}.',
    'editorSchedule.deletePeriod': 'Delete period',
    'editorSchedule.deletePeriodTitle': 'Delete period {number}?',
    'editorSchedule.deletePeriodMessage':
      'This will remove period {number} and shift the later periods forward.',
    'editorSchedule.namePlaceholder': 'Name',
    'editorSchedule.deleteBreak': 'Delete special time slot',
    'editorSchedule.timeOverlapTitle': 'Times overlap',
    'editorSchedule.timeOverlapMessage':
      'Please adjust the times so classes and special time slots do not overlap.',
    'editorSchedule.goAdjustTime': 'Go adjust the time',
    'editorSchedule.backToEditing': 'Back to editing',
    'editorTeachers.unnamedSubject': 'Unnamed subject',
    'editorTeachers.assignSubtitle': 'Choose the day and period to place "{label}"',
    'editorTeachers.periodCurrentlyIs': 'Period {number} is currently: {value}',
    'editorTeachers.periodBlank': 'Period {number} (empty)',
    'editorTeachers.overwriteSlotTitle': 'Overwrite this slot?',
    'editorTeachers.overwriteSlotMessage': 'Period {number}: change "{from}" to "{to}"?',
    'editorTeachers.confirmOverwrite': 'Confirm overwrite',
    'editorTeachers.deleteTitle': 'Delete "{label}"?',
    'editorTeachers.deleteMessage':
      'This will remove this class and clear every schedule cell that uses it.',
    'onboarding.startChoiceTitle': 'How would you like to start?',
    'onboarding.startChoiceMessage':
      'Build a schedule manually, or let AI generate one automatically from a photo.',
    'onboarding.useAiPhoto': 'Use AI to scan a photo',
    'onboarding.buildManually': 'Build it manually',
    'onboarding.welcomeTitle': 'Get started with Orbit Class',
    'onboarding.welcomeMessage':
      'If you have a code, enter it to join directly; otherwise you can build your own.',
    'onboarding.enterPairingCode': 'Enter pairing code',
    'onboarding.buildOwnFirst': 'Build my own first',
    'editorBackup.overwriteExportTitle': 'Overwrite the exported content?',
    'editorBackup.overwriteExportMessage':
      'Exporting will overwrite the content currently in the text field.',
    'editorBackup.overwriteExportConfirm':
      'Are you sure you want to replace it with the new content?',
    'editorBackup.overwriteAndExport': 'Overwrite and export',
    'editorBackup.saveFirstTitle': 'Save the current settings first?',
    'editorBackup.saveFirstMessage': 'There are unsaved changes. Save them before you {action}?',
    'editorBackup.saveThenAction': 'Save then {action}',
    'editorBackup.actionWithoutSaving': '{action} without saving',
    'editorBackup.pasteBackup': 'Please paste an Orbit Color schedule settings backup.',
    'editorBackup.noCompressionExport': 'This device does not support compressed export.',
    'editorBackup.noCompressionImport': 'This device does not support compressed import.',
    'editorBackup.mustBeJsonObject': 'The settings text must be a JSON object.',
    'editorBackup.notCreatedByThisApp':
      'This settings file was not created by the current version of Orbit_Color.',
    'editorBackup.missingField': 'The settings text is missing "{field}".',
    'editorBackup.mustBeObject': '{field} must be an object.',
    'editorBackup.mustBeArray': '{field} must be an array.',
    'editorBackup.teacherDbShape':
      'teacherDB must have every entry be a [subject, teacher, room] array.',
    'editorBackup.weeklyScheduleShape': 'weeklySchedule must have every day be an array.',
    'editorBackup.scheduleUnknownTeacher':
      'The schedule data references a teacher code that does not exist.',
    'editorBackup.invalidBellTimes': 'Period times must have a valid start and end time.',
    'editorBackup.copyFailed': 'Could not automatically copy the exported content.',
    'editorBackup.exportSuccess': 'Export content generated and copied.',
    'editorBackup.exportFailed': 'Export failed: could not create a settings backup.',
    'editorBackup.blankValue': '(blank)',
    'editorBackup.emptyValue': '(empty)',
    'editorBackup.unnamedClass': '(unnamed class)',
    'editorBackup.dayNumber': 'Day {day}',
    'editorBackup.added': 'Added {item}',
    'editorBackup.removed': 'Removed {item}',
    'editorBackup.subjectChange': '{ref} subject: {before} -> {after}',
    'editorBackup.teacherChange': '{ref} teacher: {before} -> {after}',
    'editorBackup.sectionTeachers': 'Classes and teachers',
    'editorBackup.teacherOrderChanged': 'The class order has been changed.',
    'editorBackup.locationChange': '{ref} location: {before} -> {after}',
    'editorBackup.sectionLocations': 'Class locations',
    'editorBackup.noneValue': '(none)',
    'editorBackup.periodChange': 'Period {number}: {before} -> {after}',
    'editorBackup.sectionBellTimes': 'Period times',
    'editorBackup.breakChange': 'Break {number}: {before} -> {after}',
    'editorBackup.sectionBreakTimes': 'Break times',
    'editorBackup.scheduleCellChange': '{day} period {number}: {before} -> {after}',
    'editorBackup.sectionScheduleContent': 'Schedule content',
    'editorBackup.eventChanged': 'Event: {before} -> {after}',
    'editorBackup.eventAdded': 'Added event: {event}',
    'editorBackup.eventRemoved': 'Removed event: {event}',
    'editorBackup.sectionCountdownEvents': 'Countdown events',
    'editorBackup.countdownOrderChanged': 'The countdown event order has been changed.',
    'editorBackup.reverseWeekChange': 'Odd/even week swap: {before} -> {after}',
    'editorBackup.colorChangeImport': '{label} (current): {before} -> {label} (imported): {after}',
    'editorBackup.colorChangePlain': '{label}: {before} -> {after}',
    'editorBackup.primaryColor': 'Primary color',
    'editorBackup.secondaryColor': 'Secondary color',
    'editorBackup.sectionCurrentStyle': 'Current style',
    'editorBackup.styleSlotLabel': 'Style {number}',
    'editorBackup.unnamedStyle': 'Unnamed',
    'editorBackup.styleSlotAdded':
      'Added {slot} "{name}": primary {primary}, secondary {secondary}',
    'editorBackup.styleSlotRemoved':
      'Removed {slot} "{name}": primary {primary}, secondary {secondary}',
    'editorBackup.styleSlotChangedImport':
      '{slot} "{before}" -> "{after}": primary (current) {beforePrimary} -> primary (imported) {afterPrimary}, secondary (current) {beforeSecondary} -> secondary (imported) {afterSecondary}',
    'editorBackup.styleSlotChangedPlain':
      '{slot} "{before}" -> "{after}": primary {beforePrimary} -> {afterPrimary}, secondary {beforeSecondary} -> {afterSecondary}',
    'editorBackup.sectionPersonalStyles': 'Personal styles',
    'editorBackup.noChanges': 'No changes.',
    'editorBackup.importFailedIdentical':
      'Import failed: the content is identical to the current settings.',
    'editorBackup.importFailedInvalid': 'Import failed: the content is invalid or corrupted.',
    'editorBackup.mergedClass': 'Merged class "{name}" (same name, using the imported class data)',
    'editorBackup.addedClass': 'Added class "{name}"',
    'editorBackup.replacedClassLocation': 'Replaced class "{name}" location: {before} -> {after}',
    'editorBackup.replacedDayPeriod': 'Replaced {day} period {number}: {before} -> {after}',
    'editorBackup.addedDayPeriod': 'Added {day} period {number}: {value}',
    'editorBackup.replacedBellTimes': 'Replaced period times',
    'editorBackup.addedBreak': 'Added special time slot "{name}"',
    'editorBackup.mergedBreak': 'Merged special time slot "{name}"',
    'editorBackup.replacedBreak': 'Replaced special time slot "{name}": {before} -> {after}',
    'editorBackup.removedBreakConflict':
      'Removed special time slot "{name}" (conflicts with the imported period times)',
    'editorBackup.addedCountdown': 'Added countdown event: {name} ({date})',
    'editorBackup.mergedCountdown': 'Merged countdown event: {name} ({date})',
    'editorBackup.replacedCountdown': 'Replaced countdown event: {name} ({before} -> {after})',
    'editorBackup.replacedReverseWeek': 'Replaced odd/even week setting: {value}',
    'editorBackup.importModeTitle': 'Import mode?',
    'editorBackup.importModeMessage': 'Merge the current settings with the imported settings?',
    'editorBackup.importModeHint':
      'Merge import keeps compatible content; the imported content wins on schedule time conflicts.',
    'editorBackup.mergeImport': 'Merge import',
    'editorBackup.directImport': 'Direct import',
    'editorBackup.importFailedWithReason': 'Import failed: {reason}',
    'editorBackup.importFailedTitle': 'Import failed',
    'editorBackup.importFailedMessage':
      'This import could not be completed. Please adjust and try again.',
    'editorBackup.diffAdded': 'Added:',
    'editorBackup.diffMerged': 'Merged:',
    'editorBackup.diffReplaced': 'Replaced:',
    'editorBackup.confirmMergeImportTitle': 'Confirm merge import?',
    'editorBackup.confirmDirectImportTitle': 'Confirm direct import?',
    'editorBackup.identicalImportMessage':
      'The imported content is identical to the current settings; you can still import it.',
    'editorBackup.mergeImportHint':
      'Additions, merges, and replacements are listed separately below.',
    'editorBackup.directImportWarning': 'Importing will replace the currently saved schedule data.',
    'editorBackup.identicalImportDetail': 'The content is identical; there is nothing to change.',
    'editorBackup.confirmMerge': 'Confirm merge',
    'editorBackup.confirmImport': 'Confirm import',
    'editorBackup.updatedFromOtherDevice': 'Updated from another device',
    'editorBackup.saved': 'Saved',
    'editorBackup.importedAndSaved':
      'Imported and saved. The editor has been updated with the pasted settings.',
    'editorBackup.resetAllTitle': 'Reset all data?',
    'editorBackup.resetAllMessage':
      'This will clear all data and return to the initial screen. This cannot be undone.',
    'editorBackup.resetAllDetail':
      'The schedule, style, sync settings, and more will all be cleared. Other synced devices are not affected.',
    'editorBackup.noFileSelected': 'No file selected yet',
    'nlEdit.invalidJsonResponse': 'The content AI returned is not valid JSON: {message}',
    'nlEdit.cannotConnect': 'Could not connect to the AI service: {message}',
    'nlEdit.locationBlocked':
      'The AI service is temporarily unavailable due to a server-region restriction (node: {colo}). This is usually a temporary network routing issue, please try again shortly.',
    'nlEdit.parseFailedWithStatus': 'AI instruction parsing failed ({status}): {message}',
    'nlEdit.parseFailedNoModel': 'AI instruction parsing failed: no model is available.',
    'nlEdit.locationBlockedRetrying':
      'The AI service is temporarily unavailable due to a server-region restriction (node: {colo}). Automatically retrying (attempt {attempt})…',
    'sync.rateLimited': 'Too many requests. Please try again later.',
    'sync.createFailed': 'Failed to create sync: {message}',
    'sync.notConfigured': 'Sync has not been set up yet.',
    'sync.uploadFailed': 'Sync upload failed: {message}',
    'sync.downloadFailed': 'Sync download failed: {message}',
    'sync.syncedFromOtherDevice': 'The schedule was synced from another device.',
    'sync.remoteDeletedByManager':
      'The sync was deleted entirely by the manager. This device has automatically unlinked from sync (the local schedule is unaffected).',
    'sync.copied': 'Copied!',
    'sync.copyFailed': 'Copy failed: {message}',
    'sync.roleViewer':
      'Role: receive-only (read-only) — the schedule updates automatically, but this device cannot edit it.',
    'sync.roleManager':
      'Role: manager — you can edit the schedule, and changes sync to other devices.',
    'sync.stopSyncingStyleTitle': 'Stop syncing style colors?',
    'sync.resumeSyncingStyleTitle': 'Resume syncing style colors?',
    'sync.stopSyncingStyleMessage':
      "This device's current colors will be kept, and other devices' styles will no longer be applied.",
    'sync.resumeSyncingStyleMessage':
      'The shared colors and style presets will be applied to this device immediately.',
    'sync.stopSyncingStyleDetail': 'The schedule content will continue to sync as usual.',
    'sync.resumeSyncingStyleDetail':
      'The current colors and style presets will be backed up first.',
    'sync.stopSyncingStyle': 'Stop syncing style',
    'sync.resumeSyncing': 'Resume syncing',
    'sync.styleBackupRestored': 'The kept style and style presets have been restored.',
    'sync.recoverKeptColorsTitle': 'Recover the previously kept colors?',
    'sync.recoverKeptColorsMessage':
      'Switch back to the last kept colors and style presets, or keep using the current ones?',
    'sync.switchToKeptColors': 'Switch to kept colors',
    'sync.keepCurrentColors': 'Keep current colors',
    'sync.scheduleBackupRestored': 'The local schedule from before joining sync has been restored.',
    'sync.recoverPreJoinScheduleTitle': 'Recover the schedule from before joining sync?',
    'sync.recoverPreJoinScheduleMessage':
      'Switch back to the old schedule, or keep using the just-synced schedule?',
    'sync.switchToPreJoinSchedule': 'Switch to pre-join schedule',
    'sync.keepCurrentSchedule': 'Keep current schedule',
    'sync.editLockedTitle':
      'This device only receives sync and cannot edit the schedule. Enter the manager passcode to get edit access, or unlink sync first under "Sync / Import Export".',
    'sync.editTitle': 'Edit schedule',
    'sync.styleLockedTitle':
      'This device is syncing style and cannot be changed on its own. To customize the style, first check "Do not sync style colors" in the sync panel.',
    'sync.styleToolTitle': 'Style tools',
    'sync.syncNotConfiguredContactAdmin':
      'Cross-device sync has not been set up. Please contact your schedule administrator.',
    'sync.offlineCannotCreate': 'You are currently offline, so sync cannot be created.',
    'sync.createNewSyncTitle': 'Create a new sync?',
    'sync.createNewSyncMessage': 'This will generate a new sync code and manager passcode.',
    'sync.createNewSyncDetail':
      'If you already have a code, use "Join sync" instead — slots are limited.',
    'sync.createNewSync': 'Create new sync',
    'sync.creating': 'Creating sync…',
    'sync.offlineCannotJoin': 'You are currently offline, so you cannot join sync.',
    'sync.enterPairingCode': 'Please enter the pairing code.',
    'sync.checkingCode': 'Checking pairing code…',
    'sync.codeNotFound':
      'This pairing code was not found. Please check the code, or ask the other party to press "Create new sync" first.',
    'sync.wrongManagerPasscode':
      'The manager passcode is incorrect. Please check it and try again.',
    'sync.roleManagerLabel': 'manager',
    'sync.roleViewerOnlyLabel': 'receive-only',
    'sync.joinSyncTitle': 'Join sync?',
    'sync.joinSyncMessage':
      'Joining as "{role}" will replace this device\'s current schedule, and this cannot be undone.',
    'sync.joinSyncDetail': "Other devices' schedules are not affected.",
    'sync.joinAnyway': 'Join anyway',
    'sync.joining': 'Joining sync…',
    'sync.wrongManagerPasscodeNotJoined': 'The manager passcode is incorrect. Sync was not joined.',
    'sync.joinedAsManager': 'Joined sync as manager.',
    'sync.joinedAsViewer': 'Joined sync (receive-only).',
    'sync.offlineCannotVerify':
      'You are currently offline, so the manager passcode cannot be verified.',
    'sync.enterManagerPasscode': 'Please enter the manager passcode.',
    'sync.verifyingPasscode': 'Verifying manager passcode…',
    'sync.codeNotFoundMaybeDeleted':
      'This pairing code was not found. The sync may have been deleted entirely.',
    'sync.wrongManagerPasscodePlain': 'The manager passcode is incorrect.',
    'sync.gotManagerAccess': 'Manager access granted. You can now edit the schedule.',
    'sync.unlinkCopyText': 'Sync code: {code}\nManager passcode: {passcode}',
    'sync.unlinkTitle': 'Unlink sync?',
    'sync.unlinkMessageManager':
      'This will only revert this device to a local schedule; other devices will continue syncing. Copy this before you forget the code:',
    'sync.unlinkMessageViewer':
      'Unlinking will revert to a local schedule and forget this pairing code. It is recommended to copy it first:',
    'sync.unlink': 'Unlink sync',
    'sync.unlinked': 'Sync unlinked (the local schedule is unaffected).',
    'sync.deleteForEveryone': 'Delete sync for everyone',
    'sync.copyCode': 'Copy code',
    'sync.offlineCannotDelete': 'You are currently offline, so sync cannot be deleted.',
    'sync.deleteAllTitle': 'Delete this sync entirely?',
    'sync.deleteAllMessage':
      'This will delete the shared schedule on the server. This cannot be undone.',
    'sync.deleteAllDetail':
      'The code "{code}" and manager passcode become invalid immediately; every device will revert to its own local schedule the next time it syncs.',
    'sync.deleteAll': 'Delete entirely',
    'sync.deleting': 'Deleting sync…',
    'sync.deleteFailed': 'Delete failed: {error}',
    'sync.deletedForEveryone':
      'Sync has been deleted entirely; all devices have been disconnected (local schedules are unaffected).',
    'sync.viewerLockedImport':
      'This device is in receive-only mode and cannot import. Unlink sync first if you want to edit.',
    'sync.viewerLockedSave':
      'This device is in receive-only mode and cannot save changes. Unlink sync first if you want to edit.',
    'testsim.start': 'Start',
    'testsim.pause': 'Pause',
    'testsim.resume': 'Resume',
    'testsim.versionLabel': 'Version',
    'testsim.checking': 'Checking…',
    'testsim.checkForUpdate': 'Check for update',
    'testsim.upToDate': 'Already up to date',
    'testsim.checkFailed': 'Check failed. Please check your network connection',
    'testsim.updating': 'Updating…',
    'editorCore.unnamedClassLabel': 'Unnamed',
    'editorCore.scheduleImpactLine': '{day} period {number}: {ref}',
    'editorCore.offlineMessage':
      'You are currently offline, so AI import and cross-device sync are temporarily unavailable.',
    'editorCore.dragToReorder': 'Drag to reorder',
    'editorCore.expandToEdit': 'Expand to edit',
    'editorCore.eventNameLabel': 'Event name',
    'editorCore.dateLabel': 'Date',
    'editorCore.startDateLabel': 'Start date',
    'editorCore.endDateLabel': 'End date',
    'editorCore.orderLabel': 'Order',
    'editorCore.countdownOrderAriaLabel': 'Countdown event order',
    'editorCore.removeCountdownAriaLabel': 'Remove countdown',
    'editorCore.countdownEventFallback': 'Countdown event',
    'editorCore.dragCountdownReorderAriaLabel': 'Drag to reorder countdown events',
    'editorCore.backToSchedule': 'Back to schedule',
    'editorCore.discardChangesTitle': 'Discard changes?',
    'editorCore.discardChangesMessage': 'The following unsaved changes will not be applied.',
    'editorCore.discard': 'Discard',
    'editorCore.unimportedContentTitle': 'Content not imported yet?',
    'editorCore.discardAndLeaveTransfer': 'Discard and leave',
    'editorCore.saveChangesTitle': 'Save changes?',
    'editorCore.saveChangesMessage': 'The following changes will be applied.',
    'editorCore.unimportedPastedAndAiWarning':
      'The unimported pasted content and AI recognition result will be cleared.',
    'editorCore.unimportedPastedWarning': 'The unimported pasted content will be cleared.',
    'editorCore.unimportedAiWarning': 'The unimported AI recognition result will be cleared.',
    'editorCore.unimportedGenericWarning': 'The unimported content will be cleared.',
    'editorCore.clearedUnimportedContent': 'Unimported content cleared.',
    'editorCore.aiRecognizingTitle': 'AI is recognizing',
    'editorCore.aiRecognizingMessage':
      'Please wait for recognition to finish before closing, or the result will be lost.',
    'geminiOcr.selectAFile': 'Please select a file.',
    'geminiOcr.unsupportedFileFormat':
      'Unsupported file format: {name} (JPG/PNG/HEIC/PDF are supported).',
    'geminiOcr.unnamedFile': 'unnamed file',
    'geminiOcr.fileTooLarge': 'File too large: {name}. Please use a smaller file.',
    'geminiOcr.imageLoadFailed': 'Failed to load the image. Please try a different one.',
    'geminiOcr.imageResolutionTooLow':
      'The image resolution is too low. Please use a clearer photo.',
    'geminiOcr.imageEncodeFailed': 'Failed to encode the image. Please try a different one.',
    'geminiOcr.fileReadFailed': 'Failed to read the file. Please try again.',
    'geminiOcr.notConfigured':
      'AI import has not been set up yet. Please contact your schedule administrator.',
    'geminiOcr.offline': 'You are currently offline, so AI import is temporarily unavailable.',
    'geminiOcr.selectFileFirst': 'Please select a file first.',
    'geminiOcr.requestingModel': 'Requesting the AI model ({model}) to analyze the schedule…',
    'geminiOcr.connectionFailedNextModel': 'Connection failed. Switching to the next model…',
    'geminiOcr.aiRespondedParsing':
      'AI responded (model used: {model}). Parsing the recognition result…',
    'geminiOcr.resultIncompleteRetryStronger':
      'The result from model ({model}) was incomplete. Retrying with a stronger model…',
    'geminiOcr.serviceUnavailable':
      'The AI service is currently unavailable. Please try again later.',
    'geminiOcr.recognitionFailedWithStatus': 'AI recognition request failed ({status}): {message}',
    'geminiOcr.modelUnavailableNextModel':
      'Model ({model}) is temporarily unavailable ({status}: {message}). Switching to the next model…',
    'geminiOcr.recognitionFailedNoModel': 'AI recognition request failed: no model is available.',
    'geminiOcr.noScheduleContent':
      'AI did not return any schedule content. Please try a clearer photo.',
    'geminiOcr.lunchBreakFallback': 'Lunch break',
    'geminiOcr.filePrefixedMessage': 'File {number}: {message}',
    'geminiOcr.noScheduleOrCountdownDetected':
      'No schedule photo or countdown event was detected. Please make sure the uploaded files include at least one complete weekly schedule photo, a course selection record, or a dated countdown-event notice.',
    'geminiOcr.noValidScheduleData': 'AI did not return valid schedule data.',
    'geminiOcr.noClassesOrCountdownDetected': 'No classes or countdown dates were recognized.',
    'geminiOcr.bellTimesFormatInvalid': 'The period-time data format is invalid.',
    'geminiOcr.someBellTimesFormatInvalid': 'Some period times have an invalid format.',
    'geminiOcr.scheduleDataFormatInvalid': 'The schedule data format is invalid.',
    'geminiOcr.periodsOverlapWarning':
      'Period {a} and period {b} overlap in time. Please check that the bell times are correct.',
    'geminiOcr.breakClassOverlapWarning':
      '{day} period {period} overlaps with the "{name}" time slot, but still has the class "{subject}" scheduled. Please check this is not a mistake.',
    'geminiOcr.doubleBookedWarning':
      '{day} period {periodA} "{subjectA}" and period {periodB} "{subjectB}" overlap in time, which may be a double booking.',
    'geminiOcr.periodEndNotAfterStart':
      "Period {number}'s end time is not later than its start time. Please check that the bell times are correct.",
    'geminiOcr.periodTooShort':
      'Period {number} is only {minutes} minutes long, which may be a bell-time recognition error.',
    'geminiOcr.periodTooLong':
      'Period {number} is {hours} hours long, which may be a bell-time recognition error.',
    'geminiOcr.reviewBeforeImport':
      'Please review and edit the content below as needed, then press the button to import.',
    'geminiOcr.reviewAboveBeforeImport':
      'Please confirm the content above is correct, then press the button below to import.',
    'geminiOcr.waitedSeconds': 'Waited {seconds} seconds',
    'geminiOcr.estimatedWaitTime': 'Estimated wait time: about {seconds} seconds',
    'geminiOcr.longerThanEstimated': 'Taking a bit longer than estimated, still recognizing…',
    'geminiOcr.oneFileSelected': '1 file selected',
    'geminiOcr.filesSelectedWithNames': '{count} files selected: {names}',
    'geminiOcr.tooManyFiles': 'Up to {max} files at a time. Please select fewer and try again.',
    'geminiOcr.loadedMultipleFiles':
      'Loaded {count} files. AI will automatically determine the content of each file (schedule or course selection data); the order does not affect the result.',
    'geminiOcr.loadedSingleFile':
      'File loaded. Click import to let AI automatically read the schedule.',
    'geminiOcr.viewerLockedImport':
      'This device is in receive-only mode and cannot use AI import. Unlink sync first if you want to edit.',
    'geminiOcr.preparingMultipleFiles': 'Preparing {count} files…',
    'geminiOcr.preparingFile': 'Preparing file…',
    'geminiOcr.validatingScheduleData': 'Validating schedule data…',
    'geminiOcr.recognitionCompleteReview':
      'Schedule recognition complete (model: {model}). Please review the content below before importing.',
    'geminiOcr.recognitionIncompleteManualFix':
      'The AI recognition result is incomplete. Please make manual corrections before importing.',
    'geminiOcr.importPreviewFailed': 'Import preview failed: {message}',
    'editorTeachers.subjectPlaceholder': 'Subject',
    'editorTeachers.teacherPlaceholder': 'Teacher',
    'editorTeachers.locationPlaceholderOptional': 'Room (optional)',
    'editorTeachers.subjectTeacherOrderAriaLabel': 'Subject/teacher order',
    'editorTeachers.assignPeriodAriaLabel': 'Assign period',
    'editorTeachers.assignButtonLabel': 'Assign',
    'testsim.simulating': 'Simulating',
    'dashboard.toolsLabel': 'Tools',
    'sync.transferSheetTitle': 'Sync / Import Export',
    'appearance.openStyleTools': 'Open style tools',
    'dashboard.nextPeriodInfoAriaLabel': 'Next period info',
    'dashboard.thisWeekLabel': 'This week',
    'dashboard.nextWeekLabel': 'Next week',
    'dashboard.periodsPerWeekLabel': 'Periods per week',
    'dashboard.typeLabel': 'Type',
    'dashboard.locationLabel': 'Room',
    'dashboard.occurrencesLabel': 'Occurrences',
    'common.done': 'Done',
    'editorTeachers.assignSheetTitle': 'Assign',
    'editorTeachers.chooseWeekdayAriaLabel': 'Choose weekday',
    'editorTeachers.applyAndFinish': 'Apply and finish',
    'editorCore.optionsFoldLabel': 'Options',
    'editorSchedule.reverseWeekToggleLabel': 'Swap odd/even weeks',
    'editorCore.addCountdownButton': 'Add countdown',
    'editorCore.countdownHint':
      'The home screen shows the first countdown event; swipe left or right on it to switch between events. The date can be set to a range (e.g. exam week) - for a single-day event, set the start and end date to the same day.',
    'editorTeachers.subjectsAndTeachersFoldLabel': 'Subjects and teachers',
    'common.add': 'Add',
    'editorTeachers.splitWeekHintTitle': 'Alternating-week subject/teacher',
    'editorTeachers.splitWeekHintBody':
      'Separate the two weeks with "／" when they differ (e.g. 國文／公民)',
    'editorCore.scheduleFoldLabel': 'Schedule',
    'nlEdit.headingLabel': 'AI schedule editing',
    'nlEdit.confirmBeforeApplyTag': 'Confirms before applying',
    'nlEdit.hintBody':
      'Describe what you want to change in one sentence - you can mention several things at once. AI will propose a change first, and it is only applied after you confirm it.',
    'common.submit': 'Submit',
    'editorCore.drillPeriods': 'Periods',
    'editorCore.drillBreaks': 'Time slots',
    'editorCore.drillCountdown': 'Countdown',
    'editorSchedule.addPeriodButton': 'Add period',
    'editorSchedule.specialTimeFoldLabel': 'Special time slots',
    'editorSchedule.addSpecialTimeButton': 'Add special time slot',
    'sync.syncHeading': 'Sync',
    'sync.syncHeadingTag': 'Ongoing, kept in sync across devices automatically',
    'sync.setupHint':
      'The schedule automatically syncs to every device, no account needed. The sync code can be shared freely; only the manager passcode can edit the schedule, so keep it safe.',
    'sync.orJoinExisting': 'Or join an existing sync',
    'sync.enterSyncCodePlaceholder': 'Enter sync code',
    'sync.haveManagerPasscodeSummary': 'I have the manager passcode and want edit access too',
    'sync.enterManagerPasscodePlaceholder': 'Enter manager passcode',
    'sync.joinSyncButton': 'Join sync',
    'sync.createdHint':
      "Sync created! Please save the manager passcode now - it won't be shown directly again after you leave.",
    'sync.codeLabelShareable': 'Sync code (free to share)',
    'sync.managerPasscodeLabelKeepSafe': 'Manager passcode (keep it safe)',
    'sync.savedCodeAndPasscode': "I've saved the code and passcode",
    'sync.pairedShareHint':
      'Paired with sync - share the code with other devices so they can join:',
    'sync.enterPasscodeForEditAccess': 'Enter the manager passcode to get edit access',
    'sync.getEditAccessButton': 'Get edit access',
    'sync.dontSyncStyleCheckboxLabel':
      "Don't sync style colors (keep this device's current colors)",
    'geminiOcr.headingLabel': 'AI import',
    'geminiOcr.oneTimeImportTag': 'One-time import, not automatically synced',
    'geminiOcr.setupHint':
      'Choose a schedule photo, screenshot, or PDF, and AI will automatically read it and generate a schedule. You can select multiple files to read together (e.g. a schedule photo plus a course-selection screenshot).',
    'geminiOcr.selectFileLabel': 'Select file',
    'geminiOcr.filePreviewAlt': 'File preview',
    'editorBackup.manualBackupLegacySummary': 'Manual backup (legacy, works without sync too)',
    'editorBackup.pasteBackupPlaceholder':
      'Paste your Orbit Class schedule settings backup here, or press "Export" to create one.',
    'editorBackup.copyFullBackupHint':
      'Please copy the full backup text, including the BEGIN and END markers.',
    'testsim.advancedFoldSummary': 'Advanced: time simulation',
    'testsim.previewHint':
      'Preview how the schedule looks at a given time, without affecting the real data.',
    'testsim.openTimeSimButton': 'Open time simulation',
    'geminiOcr.previewTitle': 'Recognition result and import preview',
    'geminiOcr.warningsTitle': 'May need attention',
    'geminiOcr.classesFoldLabel': 'Classes',
    'geminiOcr.assignmentFoldLabel': 'Schedule assignment',
    'geminiOcr.countdownDatesFoldLabel': 'Countdown dates',
    'geminiOcr.confirmAndImportButton': 'Confirm and import',
    'editorCore.unsavedTitle': 'Not saved yet',
    'editorCore.leaveWillDiscardChanges': 'Leaving will discard this change.',
    'testsim.timeSimAriaLabel': 'Time simulation',
    'testsim.versionLoading': 'Loading version…',
    'editorBackup.resetAllDataAriaLabel': 'Reset all data',
    'editorCore.timeHourMinuteLabel': 'Time (hour/minute)',
    'editorCore.minutesAriaLabel': 'Minutes',
    'testsim.startPauseHint':
      'After "Start", time advances automatically; after "Pause", you can change the time.',
    'testsim.exitSimButton': 'Exit simulation',
    'appearance.customColorFoldHeading': 'Custom colors',
    'appearance.colorLabel': 'Color',
    'appearance.chooseColorAriaLabel': 'Choose color',
    'appearance.styleLibraryFoldHeading': 'Style library',
    'appearance.builtInPresetsLabel': 'Built-in presets',
    'appearance.presetRose': 'Ember',
    'appearance.presetOcean': 'Lagoon',
    'appearance.presetMidnight': 'Midnight',
    'appearance.presetGraphite': 'Citrus',
    'appearance.presetAmber': 'Amber',
    'appearance.presetRuby': 'Rouge',
    'appearance.presetLilac': 'Lilac',
    'appearance.myStylesLabel': 'My styles',
    'appearance.styleSlotHint':
      'Tap the "+" next to an empty slot to save the current colors; tap it later to apply them directly.',
    'appearance.previewingNotSaved': 'Previewing, not saved yet',
    'appearance.exitPreviewButton': 'Exit preview',
    'appearance.saveStyleButton': 'Save style',
    'appearance.previewAndSaveButton': 'Preview and save',
    'common.close': 'Close',
    'editorCore.weekdayFieldLabel': 'Weekday'
  }
};

// ---- Locale detection, override, and persistence ----
//
// detectLocale() reads the browser's reported language(s) and maps anything
// starting 'zh' to 'zh-TW' and anything starting 'en' to 'en', defaulting to
// 'zh-TW' for everything else (matches the assumption test/helpers/setupEnv.js
// pins the test environment to, and Orbit Class's actual user base, which is
// Taiwanese schools).
function detectLocale() {
  const candidates = [];
  try {
    if (Array.isArray(navigator.languages)) candidates.push(...navigator.languages);
    if (navigator.language) candidates.push(navigator.language);
  } catch {
    /* navigator unavailable (non-browser environment) - fall through to default. */
  }
  for (const raw of candidates) {
    const lang = String(raw || '').toLowerCase();
    if (lang.startsWith('zh')) return 'zh-TW';
    if (lang.startsWith('en')) return 'en';
  }
  return 'zh-TW';
}

// A manual override (from the appearance/language setting) is persisted
// under its own localStorage key, the same direct-localStorage-plus-
// try/catch pattern src/onboarding.js already uses for its own standalone
// flag (ONBOARDING_SEEN_KEY) - there's no existing generic "app settings"
// store this can hook into: data.js's saveData/loadData is specifically the
// validated schedule-data schema (teacherDB/weeklySchedule/bellTimes/...),
// and a UI locale preference doesn't belong inside that shape.
const LOCALE_OVERRIDE_KEY = 'orbitLocaleOverride';

function readStoredLocaleOverride() {
  try {
    const value = localStorage.getItem(LOCALE_OVERRIDE_KEY);
    return value === 'zh-TW' || value === 'en' ? value : null;
  } catch {
    return null;
  }
}

let currentLocale = readStoredLocaleOverride() || detectLocale();

/**
 * Returns the active locale ('zh-TW' or 'en').
 */
function getLocale() {
  return currentLocale;
}

/**
 * Sets the active locale and persists it as a manual override, so it
 * survives reloads instead of being re-detected from the browser every time.
 */
function setLocale(locale) {
  currentLocale = locale === 'en' ? 'en' : 'zh-TW';
  try {
    localStorage.setItem(LOCALE_OVERRIDE_KEY, currentLocale);
  } catch {
    /* localStorage unavailable (private browsing, etc.) - the in-memory
       value above still takes effect for the rest of this session. */
  }
}

/**
 * Looks up a UI string by key in the current locale, falling back to zh-TW
 * (and then the key itself) if a locale is ever missing one. `vars`, when
 * given, fills in {name}-style placeholders in the resolved string.
 */
function t(key, vars) {
  const raw = STRINGS[currentLocale]?.[key] ?? STRINGS['zh-TW'][key] ?? key;
  if (!vars) return raw;
  return raw.replace(/\{(\w+)\}/g, (match, name) => (name in vars ? String(vars[name]) : match));
}

export { detectLocale, getLocale, setLocale, t };
